# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e26a18efe19531abfbcbe7a91d32fd4cda7b32a190346b75644ab3ffcc4cf5407fc3cab1def44d00a1fcab4b6d31cd16ba0a88b2b045ef3ae2775bdce1b5bda2

test:
  secret_key_base: 398ebe1f0bab365e15fd4e5867936983f676746888b5322aff8366b9492bff4cbc80761b752a6132fd1a6366ac46c0dcc571a646d5238f59b3fe427719e724c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
